"""
Django settings for tierzerocode project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use hardcoded key on Windows, environment variable on Linux/Docker
if platform.system() == 'Windows':
    SECRET_KEY = 'django-insecure--xvxmpo#%!0be#gh466p)4a-v3k56-8#=(^k7%ww@gmhbkuudq'
else:
    # Linux or Docker
    SECRET_KEY = os.environ.get("SECRET_KEY")

# SECRET_KEY = 'django-insecure--xvxmpo#%!0be#gh466p)4a-v3k56-8#=(^k7%ww@gmhbkuudq'

# SECURITY WARNING: don't run with debug turned on in production!
# Use DEBUG=True on Windows, environment variable on Linux/Docker
if platform.system() == 'Windows':
    DEBUG = True
else:
    # Linux or Docker
    # Environment variables are always strings, so parse "True"/"False"
    DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# DEBUG=True

# Use hardcoded hosts on Windows, environment variable on Linux/Docker
if platform.system() == 'Windows':
    ALLOWED_HOSTS = ['hersheys.tierzerocode.com','10.10.10.45','localhost']
else:
    # Linux or Docker
    ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS","127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = ['https://hersheys.tierzerocode.com']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# DISABLE CSRF FOR LOCALHOST
# SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Application definition
INSTALLED_APPS = [
    'apps.main',
    'apps.login_app',
    'apps.authhandler',
    'apps.emailhandler',
    'apps.logger',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tasks',
    # 'django_tasks.backends.database',
    'django_rq'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.login_app.middleware.ModelVerificationMiddleware', #Verifies the required models exist and redirects to setup if needed
    'apps.main.middleware.ModelVerificationMiddleware', #Verifies the required models exist and redirects to setup if needed
    'apps.authhandler.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tierzerocode.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tierzerocode.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use SQLite on Windows, PostgreSQL/MySQL on Linux/Docker
if platform.system() == 'Windows':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Linux or Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.{}'.format(
                os.getenv('DATABASE_ENGINE', 'postgresql_psycopg2')
            ),
            'NAME': os.getenv('DATABASE_NAME', 'dockerdjango'),
            'USER': os.getenv('DATABASE_USER', 'dbuser'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', 'dbpassword'),
            'HOST': os.getenv('DATABASE_HOST', 'db'),
            'PORT': os.getenv('DATABASE_PORT', 5432),
        }
    }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dockerdjango',
#         'USER': 'dbuser',
#         'PASSWORD': 'dbpassword',
#         'HOST': '172.17.0.2',
#         'PORT': 5432,
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',                    # Default backend
    'apps.authhandler.authentication_backends.MicrosoftEntraID.MicrosoftEntraIDBackend',  # Microsoft Entra ID backend
]

TASKS = {
    'default': {
        # 'BACKEND': 'django_tasks.backends.database.DatabaseBackend',
        'BACKEND': 'django_tasks.backends.rq.RQBackend',
        'QUEUES': ['default'],
    }
}

# Redis Queue configuration - use environment variables in Docker, hardcoded on Windows
if platform.system() == 'Windows':
    RQ_QUEUES = {
        'default': {
            'HOST': '172.17.0.3',  # or 'localhost'
            'PORT': 6379,
            'DB': 0,
            'DEFAULT_TIMEOUT': 7200,  # 2 hours - max time a job can run before being killed
            'DEFAULT_RESULT_TTL': 10800,  # 3 hours - how long job results are kept in Redis
        }
    }
else:
    # Linux or Docker - use environment variables
    RQ_QUEUES = {
        'default': {
            'HOST': os.getenv('REDIS_HOST', 'redis'),
            'PORT': int(os.getenv('REDIS_PORT', '6379')),
            'DB': int(os.getenv('REDIS_DB', '0')),
            'DEFAULT_TIMEOUT': 7200,  # 2 hours - max time a job can run before being killed
            'DEFAULT_RESULT_TTL': 10800,  # 3 hours - how long job results are kept in Redis
        }
    }


# Ensure django-rq admin link is shown (default is True, but explicit for clarity)
RQ_SHOW_ADMIN_LINK = True

# TASKS_BACKEND = 'django.tasks.backends.database.DatabaseBackend'
# TASKS_QUEUES = ['entraidusersync']

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True

# Disable automatic trailing slash appending
APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
# Ensure static directory exists
os.makedirs(STATIC_ROOT, exist_ok=True)

LOGIN_URL = '/identity/login'

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('pt', 'Portuguese'),
    ('zh-hans', 'Simplified Chinese'),
]

# django-admin makemessages -l en
# django-admin compilemessages

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]