"""
Django settings for template project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os # Added for environment variables and platform detection

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS","localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'apps.main', # Main application
    'apps.login_app', # Login application
    'apps.authhandler', # Authentication handler application
    'apps.emailhandler', # Email handler application
    'apps.logger', # Logger application
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tasks', # Django tasks
    'django_rq', # Django RQ
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.authhandler.middleware.AuthenticationMiddleware', # Custom middleware to verify the required models exist and redirects to setup if needed
    'apps.main.middleware.ModelVerificationMiddleware', # Custom middleware to verify the required models exist and redirects to setup if needed
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tierzerocode.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tierzerocode.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DJANGO_DEV"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.{}'.format(
                os.getenv('DATABASE_ENGINE', 'postgresql_psycopg2')
            ),
            'NAME': os.getenv('DATABASE_NAME', 'dockerdjango'),
            'USER': os.getenv('DATABASE_USER', 'dbuser'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', 'dbpassword'),
            'HOST': os.getenv('DATABASE_HOST', 'db'),
            'PORT': os.getenv('DATABASE_PORT', 5432),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


##################################################################################################################

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',                    # Default backend
    'apps.authhandler.authentication_backends.MicrosoftEntraID.MicrosoftEntraIDBackend',  # Microsoft Entra ID backend
]

if os.environ.get("DJANGO_DEV"):
    TASKS = {
        'default': {
            'BACKEND': 'django_tasks.backends.immediate.ImmediateBackend',
            'QUEUES': ['default'],
        }
    }
else:
    TASKS = {
        'default': {
            'BACKEND': 'django_tasks.backends.rq.RQBackend',
            'QUEUES': ['default'],
        }
    }

# Redis Queue configuration - use environment variables in Docker, hardcoded on Windows
RQ_QUEUES = {
    'default': {
        'HOST': os.getenv('REDIS_HOST', 'redis'),
        'PORT': int(os.getenv('REDIS_PORT', '6379')),
        'DB': int(os.getenv('REDIS_DB', '0')),
        'DEFAULT_TIMEOUT': 7200,  # 2 hours - max time a job can run before being killed
        'DEFAULT_RESULT_TTL': 10800,  # 3 hours - how long job results are kept in Redis
    }
}


# Ensure django-rq admin link is shown (default is True, but explicit for clarity)
RQ_SHOW_ADMIN_LINK = True
# Disable automatic trailing slash appending
APPEND_SLASH = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
# Ensure static directory exists
os.makedirs(STATIC_ROOT, exist_ok=True)

LOGIN_URL = '/identity/login'

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('pt', 'Portuguese'),
    ('zh-hans', 'Simplified Chinese'),
]

# django-admin makemessages -l en
# django-admin compilemessages

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]


# Reverse proxy SSL configuration (trust X-Forwarded-Proto header to detect HTTPS and prevent redirect loops)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trust X-Forwarded-Host header so Django identifies the hostname from the reverse proxy
USE_X_FORWARDED_HOST = True

# Secure cookies depend on USE_HTTPS (True behind SSL-terminating reverse proxies, override with USE_HTTPS=False if HTTP is required)
USE_HTTPS = os.environ.get("USE_HTTPS", "True").lower() == "true"

# SECURE_SSL_REDIRECT must be False behind a reverse proxy to avoid redirect loops (proxy handles HTTP→HTTPS)
SECURE_SSL_REDIRECT = False

# Secure cookie settings for SSL-terminating reverse proxies (set USE_HTTPS=True so Django treats requests as HTTPS)
CSRF_COOKIE_SECURE = USE_HTTPS
SESSION_COOKIE_SECURE = USE_HTTPS

# HSTS disabled behind reverse proxies to avoid issues; proxy should manage HSTS headers instead
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Generate CSRF_TRUSTED_ORIGINS from ALLOWED_HOSTS using both http/https and common ports
CSRF_TRUSTED_ORIGINS = []
WEB_PORT = os.environ.get("WEB_PORT", "8000")
common_ports = ["", f":{WEB_PORT}", ":80", ":443", ":8000", ":8080"]

for host in ALLOWED_HOSTS:
    host = host.strip()  # Remove any whitespace
    if host:  # Only add non-empty hosts
        # Check if host already includes a port
        if ':' in host:
            # Host already has a port, use it as-is
            CSRF_TRUSTED_ORIGINS.extend([
                f"http://{host}",
                f"https://{host}"
            ])
        else:
            # Add host with common ports
            for port in common_ports:
                CSRF_TRUSTED_ORIGINS.extend([
                    f"http://{host}{port}",
                    f"https://{host}{port}"
                ])

# Remove duplicates while preserving order
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))