# Generated by Django 5.2.6 on 2025-09-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssointegration',
            options={'verbose_name': 'SSO Integration', 'verbose_name_plural': 'SSO Integrations'},
        ),
    ]
