# Generated by Django 5.0.7 on 2024-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=4)),
                ('event_type', models.CharField(max_length=50)),
                ('event_group', models.CharField(max_length=50)),
                ('user_level', models.CharField(max_length=50)),
                ('privledged', models.BooleanField(default=True)),
                ('action', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=20)),
                ('additional_data', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
