# Generated by Django 6.0.2 on 2026-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('logger', '0001_initial'), ('logger', '0002_rename_privledged_log_privileged_log_browser_and_more'), ('logger', '0003_log_session_id')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=4)),
                ('event_type', models.CharField(max_length=50)),
                ('event_group', models.CharField(max_length=50)),
                ('user_level', models.CharField(max_length=50)),
                ('privileged', models.BooleanField(default=True)),
                ('action', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=20)),
                ('additional_data', models.CharField(max_length=250)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('browser', models.CharField(blank=True, max_length=250, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=250, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
