# Generated by Django 6.0 on 2025-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='privledged',
            new_name='privileged',
        ),
        migrations.AddField(
            model_name='log',
            name='browser',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='operating_system',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
