# Generated by Django 6.0 on 2025-12-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_rename_privledged_log_privileged_log_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
