from django.db import models

# DeviceManagementManagedDevices.Read.All
class IntuneDevice(models.Model):
    id = models.CharField(max_length = 100, primary_key=True)
    userId = models.CharField(max_length = 50)
    deviceName = models.CharField(max_length = 100)
    managedDeviceOwnerType = models.CharField(max_length = 25)
    enrolledDateTime = models.DateTimeField()
    lastSyncDateTime = models.DateTimeField()
    operatingSystem = models.CharField(max_length = 25)
    complianceState = models.CharField(max_length = 25)
    jailBroken = models.CharField(max_length = 25)
    managementAgent = models.CharField(max_length = 20)
    osVersion = models.CharField(max_length = 25)
    easActivated = models.BooleanField()
    easDeviceId = models.CharField(max_length = 50)
    easActivationDateTime = models.DateTimeField()
    azureADRegistered = models.BooleanField()
    deviceEnrollmentType = models.CharField(max_length = 50)
    activationLockBypassCode = models.CharField(max_length = 50)
    emailAddress = models.EmailField(max_length = 100)
    azureADDeviceId = models.CharField(max_length = 50)
    deviceRegistrationState = models.CharField(max_length = 50)
    deviceCategoryDisplayName = models.CharField(max_length = 50)
    isSupervised = models.BooleanField()
    exchangeLastSuccessfulSyncDateTime = models.DateTimeField()
    exchangeAccessState = models.CharField(max_length = 50)
    exchangeAccessStateReason = models.CharField(max_length = 50)
    remoteAssistanceSessionUrl = models.CharField(max_length = 50)
    remoteAssistanceSessionErrorDetails = models.CharField(max_length = 50)
    isEncrypted = models.BooleanField()
    userPrincipalName = models.CharField(max_length = 50)
    model = models.CharField(max_length = 50)
    manufacturer = models.CharField(max_length = 50)
    imei = models.CharField(max_length = 50)
    complianceGracePeriodExpirationDateTime = models.DateTimeField()
    serialNumber = models.CharField(max_length = 50)
    phoneNumber = models.CharField(max_length = 50)
    androidSecurityPatchLevel = models.CharField(max_length = 50)
    userDisplayName = models.CharField(max_length = 100)
    configurationManagerClientEnabledFeatures = models.CharField(max_length = 50)
    wiFiMacAddress = models.CharField(max_length = 50)
    deviceHealthAttestationState = models.CharField(max_length = 50)
    subscriberCarrier = models.CharField(max_length = 50)
    meid = models.CharField(max_length = 50)
    totalStorageSpaceInBytes = models.IntegerField()
    freeStorageSpaceInBytes = models.IntegerField()
    managedDeviceName = models.CharField(max_length = 200)
    partnerReportedThreatState = models.CharField(max_length = 50)
    requireUserEnrollmentApproval = models.CharField(max_length = 50)
    managementCertificateExpirationDate = models.DateTimeField()
    iccid = models.CharField(max_length = 50)
    udid = models.CharField(max_length = 50)
    notes = models.CharField(max_length = 500)
    ethernetMacAddress = models.CharField(max_length = 50)
    physicalMemoryInBytes = models.IntegerField()
    # deviceActionResults = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.deviceName