# Generated by Django 5.2.6 on 2025-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, null=True)),
                ('integration_type', models.CharField(choices=[('Microsoft 365', 'Microsoft 365')], max_length=25, null=True)),
                ('image_navbar_path', models.CharField(max_length=100, null=True)),
                ('image_integration_path', models.CharField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('client_secret', models.CharField(max_length=200, null=True)),
                ('tenant_id', models.CharField(max_length=200, null=True)),
                ('tenant_domain', models.CharField(max_length=200, null=True)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Integration',
                'verbose_name_plural': 'Email Integrations',
            },
        ),
    ]
