# Generated by Django 6.0.2 on 2026-02-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('login_app', '0001_initial'), ('login_app', '0002_user_permission'), ('login_app', '0003_alter_user_permission'), ('login_app', '0004_ssointegration_delete_user'), ('login_app', '0005_delete_ssointegration')]

    dependencies = [
    ]

    operations = [
    ]
