# Generated by Django 3.2.2 on 2021-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('admininistrator', 'Administrator'), ('standard', 'Standard')], default='administrator', max_length=20, verbose_name='Permission'),
            preserve_default=False,
        ),
    ]
