# Generated by Django 3.2.2 on 2021-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('standard', 'Standard')], max_length=20, verbose_name='Permission'),
        ),
    ]
