# Generated by Django 6.0 on 2026-01-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_ssointegration_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSOIntegration',
        ),
    ]
