# Generated by Django 5.0.2 on 2024-02-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intunedevice',
            name='activationLockBypassCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='androidSecurityPatchLevel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='azureADDeviceId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='azureADRegistered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='complianceGracePeriodExpirationDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='complianceState',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='configurationManagerClientEnabledFeatures',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='deviceCategoryDisplayName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='deviceEnrollmentType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='deviceHealthAttestationState',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='deviceName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='deviceRegistrationState',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='easActivated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='easActivationDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='easDeviceId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='emailAddress',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='enrolledDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='ethernetMacAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='exchangeAccessState',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='exchangeAccessStateReason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='exchangeLastSuccessfulSyncDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='freeStorageSpaceInBytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='iccid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='imei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='isEncrypted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='isSupervised',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='jailBroken',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='lastSyncDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='managedDeviceName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='managedDeviceOwnerType',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='managementAgent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='managementCertificateExpirationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='meid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='operatingSystem',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='osVersion',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='partnerReportedThreatState',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='phoneNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='physicalMemoryInBytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='remoteAssistanceSessionErrorDetails',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='remoteAssistanceSessionUrl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='requireUserEnrollmentApproval',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='serialNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='subscriberCarrier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='totalStorageSpaceInBytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='udid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='userDisplayName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='userId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='userPrincipalName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='wiFiMacAddress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
