# Generated by Django 5.0.2 on 2024-02-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_intunedevice_activationlockbypasscode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntuneIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, null=True)),
                ('client_secret', models.CharField(max_length=50, null=True)),
                ('tenant_id', models.CharField(max_length=50, null=True)),
                ('tenant_domain', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
