# Generated by Django 5.0.2 on 2024-02-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_intuneintegration_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SophosDevice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('tenant_id', models.CharField(max_length=100)),
                ('os_isServer', models.BooleanField(null=True)),
                ('os_platform', models.CharField(max_length=50)),
                ('os_name', models.CharField(max_length=100)),
                ('os_majorVersion', models.CharField(max_length=100)),
                ('os_minorVersion', models.CharField(max_length=100)),
                ('os_build', models.CharField(max_length=100)),
                ('ipv4Addresses', models.CharField(max_length=50)),
                ('macAddresses', models.CharField(max_length=50)),
                ('associatedPerson_viaLogin', models.CharField(max_length=50)),
                ('tamperProtectionEnabled', models.BooleanField(null=True)),
                ('lastSeenAt', models.DateTimeField(null=True)),
                ('lockdown_status', models.CharField(max_length=50)),
                ('lockdown_updateStatus', models.CharField(max_length=50)),
                ('isolation_status', models.CharField(max_length=50)),
                ('isolation_adminIsolated', models.BooleanField(null=True)),
                ('isolation_selfIsolated', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='intunedevice',
            name='totalStorageSpaceInBytes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
