# Generated by Django 5.0.2 on 2024-02-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sophosdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sophosdevice',
            name='associatedPerson_viaLogin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='hostname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='ipv4Addresses',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='isolation_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='lockdown_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='lockdown_updateStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='macAddresses',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='os_build',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='os_majorVersion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='os_minorVersion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='os_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='os_platform',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='tenant_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
