# Generated by Django 5.0.2 on 2024-02-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sophosdevice_associatedperson_vialogin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='intunedevice',
            name='parentDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.device'),
        ),
    ]
