# Generated by Django 5.0.2 on 2024-02-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_device_intunedevice_parentdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sophosdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sophosdevice',
            name='parentDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.device'),
        ),
        migrations.AddField(
            model_name='sophosdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
