# Generated by Django 5.0.2 on 2024-02-19 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sophosdevice_created_at_sophosdevice_parentdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intunedevice',
            name='parentDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationIntune', to='main.device'),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='parentDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationSophos', to='main.device'),
        ),
    ]
