# Generated by Django 5.0.2 on 2024-02-19 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_defenderintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenderDevice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mergedIntoMachineId', models.CharField(max_length=50, null=True)),
                ('isPotentialDuplication', models.BooleanField(null=True)),
                ('isExcluded', models.BooleanField(null=True)),
                ('exclusionReason', models.CharField(max_length=50, null=True)),
                ('computerDnsName', models.CharField(max_length=100, null=True)),
                ('firstSeen', models.DateTimeField(null=True)),
                ('lastSeen', models.DateTimeField(null=True)),
                ('osPlatform', models.CharField(max_length=50, null=True)),
                ('osVersion', models.CharField(max_length=50, null=True)),
                ('osProcessor', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('lastIpAddress', models.CharField(max_length=50, null=True)),
                ('lastExternalIpAddress', models.CharField(max_length=50, null=True)),
                ('agentVersion', models.CharField(max_length=50, null=True)),
                ('osBuild', models.IntegerField(null=True)),
                ('healthStatus', models.CharField(max_length=50, null=True)),
                ('deviceValue', models.CharField(max_length=50, null=True)),
                ('rbacGroupId', models.IntegerField(null=True)),
                ('rbacGroupName', models.CharField(max_length=50, null=True)),
                ('riskScore', models.CharField(max_length=50, null=True)),
                ('exposureLevel', models.CharField(max_length=50, null=True)),
                ('isAadJoined', models.BooleanField(null=True)),
                ('aadDeviceId', models.CharField(max_length=50, null=True)),
                ('defenderAvStatus', models.CharField(max_length=50, null=True)),
                ('onboardingStatus', models.CharField(max_length=50, null=True)),
                ('osArchitecture', models.CharField(max_length=50, null=True)),
                ('managedBy', models.CharField(max_length=50, null=True)),
                ('managedByStatus', models.CharField(max_length=50, null=True)),
                ('vmMetadata', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parentDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationDefender', to='main.device')),
            ],
        ),
    ]
