# Generated by Django 5.0.2 on 2024-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_defenderdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenderintegration',
            name='enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='intuneintegration',
            name='enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sophosintegration',
            name='enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
