# Generated by Django 5.0.2 on 2024-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_defenderintegration_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenderdevice',
            name='firstSeen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defenderdevice',
            name='lastSeen',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
