# Generated by Django 5.0.2 on 2024-02-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_qualysintegration_sccmintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
