# Generated by Django 5.0.2 on 2024-02-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_device_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intunedevice',
            old_name='operatingSystem',
            new_name='osPlatform',
        ),
    ]
