# Generated by Django 5.0.2 on 2024-02-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_operatingsystem_intunedevice_osplatform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sophosdevice',
            old_name='os_platform',
            new_name='osPlatform',
        ),
    ]
