# Generated by Django 5.0.2 on 2024-02-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_os_platform_sophosdevice_osplatform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='os',
            new_name='osPlatform',
        ),
    ]
