# Generated by Django 5.0.2 on 2024-02-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_os_device_osplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='endpointType',
            field=models.CharField(choices=[('MOBILE', 'Mobile'), ('CLIENT', 'Client'), ('SERVER', 'Server')], max_length=9, null=True),
        ),
    ]
