# Generated by Django 5.0.2 on 2024-02-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_device_endpointtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='endpointType',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SERVER', 'Server'), ('MOBILE', 'Mobile')], max_length=9, null=True),
        ),
    ]
