# Generated by Django 5.0.2 on 2024-02-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_device_endpointtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='endpointType',
            field=models.CharField(choices=[('Client', 'Client'), ('Server', 'Server'), ('Mobile', 'Mobile')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='osPlatform',
            field=models.CharField(choices=[('Android', 'Android'), ('Ubuntu', 'Ubuntu'), ('Windows', 'Windows'), ('Windows Server', 'Windows Server')], max_length=20, null=True),
        ),
    ]
