# Generated by Django 5.0.2 on 2024-02-21 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_crowdstrikeintegration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intunedevice',
            old_name='deviceName',
            new_name='hostname',
        ),
    ]
