# Generated by Django 5.0.2 on 2024-02-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_devicename_intunedevice_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defenderdevice',
            old_name='computerDnsName',
            new_name='hostname',
        ),
    ]
