# Generated by Django 5.0.2 on 2024-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_computerdnsname_defenderdevice_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='intunedevice',
            name='endpointType',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
