# Generated by Django 5.0.2 on 2024-03-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_intunedevice_endpointtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenderdevice',
            name='endpointType',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='sophosdevice',
            name='endpointType',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
