# Generated by Django 5.0.2 on 2024-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_integration_delete_integrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='client_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='client_secret',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
