# Generated by Django 5.0.2 on 2024-03-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_integration_client_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrowdStrikeIntegration',
        ),
        migrations.DeleteModel(
            name='DefenderIntegration',
        ),
        migrations.DeleteModel(
            name='IntuneIntegration',
        ),
        migrations.DeleteModel(
            name='QualysIntegration',
        ),
        migrations.DeleteModel(
            name='SCCMIntegration',
        ),
        migrations.DeleteModel(
            name='SophosIntegration',
        ),
    ]
