# Generated by Django 5.0.2 on 2024-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_delete_crowdstrikeintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('Microsoft Intune', 'Microsoft Intune'), ('Sophos Central', 'Sophos Central'), ('Microsoft Defender for Endpoint', 'Microsoft Defender for Endpoint'), ('CrowdStrike Falcon', 'CrowdStrike Falcon'), ('System Center Configuration Manager', 'System Center Configuration Manager'), ('Qualys', 'Qualys')], max_length=35, null=True),
        ),
    ]
