# Generated by Django 5.0.2 on 2024-03-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_integration_integration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualysDevice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, null=True)),
                ('osPlatform', models.CharField(max_length=50, null=True)),
                ('firstFoundDate', models.CharField(max_length=50, null=True)),
                ('ipAddress', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parentDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationQualys', to='main.device')),
            ],
        ),
    ]
