# Generated by Django 5.0.2 on 2024-03-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_device_endpointtype_alter_device_osplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='image_integration_page',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='integration',
            name='image_navbar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
