# Generated by Django 5.0.2 on 2024-03-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_integration_image_integration_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='image_integration_page',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='image_navbar',
        ),
        migrations.AddField(
            model_name='integration',
            name='image_integration_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='image_navbar_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
