# Generated by Django 5.0.2 on 2024-03-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_integration_integration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftentraiddevice',
            name='deviceId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
