# Generated by Django 5.0.2 on 2024-03-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_device_osplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='osPlatform',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS/iPadOS', 'iOS/iPadOS'), ('MacOS', 'MacOS'), ('Ubuntu', 'Ubuntu'), ('Windows', 'Windows'), ('Windows Server', 'Windows Server'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
