# Generated by Django 5.0.2 on 2024-03-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_device_osplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defenderdevice',
            name='exclusionReason',
        ),
        migrations.RemoveField(
            model_name='defenderdevice',
            name='isExcluded',
        ),
        migrations.RemoveField(
            model_name='defenderdevice',
            name='isPotentialDuplication',
        ),
        migrations.RemoveField(
            model_name='defenderdevice',
            name='lastExternalIpAddress',
        ),
        migrations.RemoveField(
            model_name='defenderdevice',
            name='lastIpAddress',
        ),
        migrations.RemoveField(
            model_name='defenderdevice',
            name='mergedIntoMachineId',
        ),
    ]
