# Generated by Django 5.0.2 on 2024-03-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_defenderdevice_exclusionreason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceComplianceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(null=True)),
            ],
        ),
    ]
