# Generated by Django 5.0.2 on 2024-04-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_device_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='integration_type_short',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
