# Generated by Django 5.0.2 on 2024-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_microsoftentraiddevice_parentdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
