# Generated by Django 5.0.2 on 2024-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_integration_created_at_integration_last_synced_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecompliancesettings',
            name='settings',
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='compliance_crowdstrike_falcon',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='compliance_microsoft_defender_for_endpoint',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='compliance_microsoft_entra_id',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='compliance_microsoft_intune',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='compliance_qualys',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='compliance_sophos_central',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
