# Generated by Django 5.0.2 on 2024-05-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_devicecompliancesettings_settings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecompliancesettings',
            old_name='compliance_crowdstrike_falcon',
            new_name='crowdstrike_falcon',
        ),
        migrations.RenameField(
            model_name='devicecompliancesettings',
            old_name='compliance_microsoft_defender_for_endpoint',
            new_name='microsoft_defender_for_endpoint',
        ),
        migrations.RenameField(
            model_name='devicecompliancesettings',
            old_name='compliance_microsoft_entra_id',
            new_name='microsoft_entra_id',
        ),
        migrations.RenameField(
            model_name='devicecompliancesettings',
            old_name='compliance_microsoft_intune',
            new_name='microsoft_intune',
        ),
        migrations.RenameField(
            model_name='devicecompliancesettings',
            old_name='compliance_qualys',
            new_name='qualys',
        ),
        migrations.RenameField(
            model_name='devicecompliancesettings',
            old_name='compliance_sophos_central',
            new_name='sophos_central',
        ),
    ]
