# Generated by Django 5.0.2 on 2024-05-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_rename_compliance_crowdstrike_falcon_devicecompliancesettings_crowdstrike_falcon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upn', models.EmailField(max_length=100, null=True)),
                ('uid', models.CharField(max_length=150, null=True)),
                ('given_name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('email_authentication_method', models.BooleanField(null=True)),
                ('fido2_authentication_method', models.BooleanField(null=True)),
                ('microsoft_authenticator_authentication_method', models.BooleanField(null=True)),
                ('password_authentication_method', models.BooleanField(null=True)),
                ('phone_authentication_method', models.BooleanField(null=True)),
                ('software_oath_authentication_method', models.BooleanField(null=True)),
                ('temporary_access_pass_authentication_method', models.BooleanField(null=True)),
                ('windows_hello_for_business_authentication_method', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
