# Generated by Django 5.0.2 on 2024-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='integration_context',
            field=models.CharField(choices=[('Cloud Configuration', 'Cloud Configuration'), ('Device', 'Device'), ('User', 'User')], max_length=35, null=True),
        ),
    ]
