# Generated by Django 5.0.2 on 2024-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_integration_integration_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='integration',
            field=models.ManyToManyField(null=True, related_name='users', to='main.integration'),
        ),
    ]
