# Generated by Django 5.0.2 on 2024-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_microsoftintunedevicedata_activationlockbypasscode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftintunedevicedata',
            name='enrollmentProfileName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
