# Generated by Django 5.0.2 on 2024-05-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_microsoftentraiddevicedata_accountenabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoftentraiddevicedata',
            name='physicalIds_GID',
        ),
        migrations.RemoveField(
            model_name='microsoftentraiddevicedata',
            name='physicalIds_HWID',
        ),
        migrations.RemoveField(
            model_name='microsoftentraiddevicedata',
            name='physicalIds_ZTDID',
        ),
    ]
