# Generated by Django 5.0.2 on 2024-05-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_microsoftentraiddevicedata_physicalids_gid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsoftentraiddevicedata',
            old_name='deivceMetadata',
            new_name='deviceMetadata',
        ),
    ]
