# Generated by Django 5.0.2 on 2024-05-25 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_cloudflarezerotrustdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftDefenderforEndpointDevice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, null=True)),
                ('firstSeen', models.CharField(max_length=50, null=True)),
                ('lastSeen', models.CharField(max_length=50, null=True)),
                ('osPlatform', models.CharField(max_length=50, null=True)),
                ('endpointType', models.CharField(max_length=25, null=True)),
                ('osVersion', models.CharField(max_length=50, null=True)),
                ('osProcessor', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('agentVersion', models.CharField(max_length=50, null=True)),
                ('osBuild', models.IntegerField(null=True)),
                ('healthStatus', models.CharField(max_length=50, null=True)),
                ('deviceValue', models.CharField(max_length=50, null=True)),
                ('rbacGroupId', models.IntegerField(null=True)),
                ('rbacGroupName', models.CharField(max_length=50, null=True)),
                ('riskScore', models.CharField(max_length=50, null=True)),
                ('exposureLevel', models.CharField(max_length=50, null=True)),
                ('isAadJoined', models.BooleanField(null=True)),
                ('aadDeviceId', models.CharField(max_length=50, null=True)),
                ('defenderAvStatus', models.CharField(max_length=50, null=True)),
                ('onboardingStatus', models.CharField(max_length=50, null=True)),
                ('osArchitecture', models.CharField(max_length=50, null=True)),
                ('managedBy', models.CharField(max_length=50, null=True)),
                ('managedByStatus', models.CharField(max_length=50, null=True)),
                ('vmMetadata', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parentDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationMicrosoftDefenderForEndpoint', to='main.device')),
            ],
        ),
        migrations.DeleteModel(
            name='DefenderDevice',
        ),
    ]
