# Generated by Django 5.0.2 on 2024-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_rename_microsoftdefenderforendpointdevice_microsoftdefenderforendpointdevicedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsoftdefenderforendpointdevicedata',
            old_name='hostname',
            new_name='computerDnsName',
        ),
        migrations.RemoveField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='endpointType',
        ),
        migrations.AddField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='excludeReason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='isExcluded',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='isPotentialDuplication',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastExternalIpAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastIpAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='mergedIntoMachineId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
