# Generated by Django 5.0.2 on 2024-05-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_rename_hostname_microsoftdefenderforendpointdevicedata_computerdnsname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsoftdefenderforendpointdevicedata',
            old_name='excludeReason',
            new_name='exclusionReason',
        ),
    ]
