# Generated by Django 5.0.6 on 2024-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_device_integration_alter_userdata_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='osPlatform',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS/iPadOS', 'iOS/iPadOS'), ('MacOS', 'MacOS'), ('Red Hat Enterprise Linux', 'Red Hat Enterprise Linux'), ('Ubuntu', 'Ubuntu'), ('Windows', 'Windows'), ('Windows Server', 'Windows Server'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
