# Generated by Django 5.0.6 on 2024-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_device_osplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='osPlatform',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS/iPadOS', 'iOS/iPadOS'), ('MacOS', 'MacOS'), ('Red Hat Enterprise Linux', 'Red Hat Enterprise Linux'), ('CentOS', 'CentOS'), ('Ubuntu', 'Ubuntu'), ('Windows', 'Windows'), ('Windows Server', 'Windows Server'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
