# Generated by Django 5.0.2 on 2024-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_crowdstrikefalcondevicedata_agent_load_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='domainName',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='hostname',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
