# Generated by Django 5.0.2 on 2024-05-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_device_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudflarezerotrustdevice',
            name='osPlatform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant_domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='aadDeviceId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='agentVersion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='defenderAvStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='deviceValue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='exclusionReason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='exposureLevel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='firstSeen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='healthStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastExternalIpAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastIpAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastSeen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='managedBy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='managedByStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='mergedIntoMachineId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='onboardingStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osArchitecture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osPlatform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osProcessor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osVersion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='rbacGroupName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='riskScore',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='vmMetadata',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceMetadata',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceOwnership',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceVersion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='displayName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='enrollmentProfileName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='enrollmentType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='externalSourceName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='managementType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='mdmAppId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='operatingSystem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='operatingSystemVersion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='profileType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='sourceType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='trustType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='activationLockBypassCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='androidSecurityPatchLevel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='azureADDeviceId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='configurationManagerClientEnabledFeatures',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceCategoryDisplayName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceEnrollmentType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceHealthAttestationState',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceRegistrationState',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='easDeviceId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='enrollmentProfileName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='ethernetMacAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='exchangeAccessState',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='exchangeAccessStateReason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='iccid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='imei',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='meid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='partnerReportedThreatState',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='phoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='remoteAssistanceSessionErrorDetails',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='remoteAssistanceSessionUrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='requireUserEnrollmentApproval',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='serialNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='subscriberCarrier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='udid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='userId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='userPrincipalName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='wiFiMacAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='firstFoundDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='ipAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='osPlatform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='associatedPerson_viaLogin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='ipv4Addresses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='isolation_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='lockdown_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='lockdown_updateStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='macAddresses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='osPlatform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophosdevice',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='given_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
