# Generated by Django 5.0.2 on 2024-06-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_microsoftdefenderforendpointdevicedata_osbuild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
