# Generated by Django 5.0.6 on 2024-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_sophoscentraldevicedata_delete_sophosdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='managementAgent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
