# Generated by Django 5.0.6 on 2024-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_alter_microsoftintunedevicedata_managementagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudflarezerotrustdevice',
            name='hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudflarezerotrustdevice',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudflarezerotrustdevice',
            name='osPlatform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='agent_load_flags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='agent_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='base_image_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='bios_manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='bios_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='build_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='chassis_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='chassis_type_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='cid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='config_id_base',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='config_id_build',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='config_id_platform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='connection_ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='connection_mac_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='cpu_signature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='cpu_vendor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='default_gateway_ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='deployment_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='detection_suppression_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='external_ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='group_hash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='host_hidden_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='host_utc_offset',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='instance_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='internet_exposure',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='k8s_cluster_git_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='k8s_cluster_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='k8s_cluster_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='kernel_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='last_login_uid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='last_login_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='last_login_user_sid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='linux_sensor_mode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='local_ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='mac_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='machine_domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='major_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='minor_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='os_build',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='os_product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='os_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='platform_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='platform_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_host_ip4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_host_ip6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_ip4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_ip6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_namespace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pod_service_account_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='pointer_size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='product_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='product_type_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='provision_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='reduced_functionality_mode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='release_group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='rtr_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='serial_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='service_pack_major',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='service_pack_minor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='service_provider',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='service_provider_account_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='site_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='system_manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='system_product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstrikefalcondevicedata',
            name='zone_group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicecompliancesettings',
            name='os_platform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='client_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='image_integration_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='image_navbar_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant_domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='aadDeviceId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='agentVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='computerDnsName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='defenderAvStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='deviceValue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='exclusionReason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='exposureLevel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='firstSeen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='healthStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastExternalIpAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastIpAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='lastSeen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='managedBy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='managedByStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='mergedIntoMachineId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='onboardingStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osArchitecture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osPlatform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osProcessor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='osVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='rbacGroupName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='riskScore',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftdefenderforendpointdevicedata',
            name='vmMetadata',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceCategory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceMetadata',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceOwnership',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='deviceVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='displayName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='enrollmentProfileName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='enrollmentType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='externalSourceName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='managementType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='mdmAppId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='operatingSystem',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='operatingSystemVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='profileType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='sourceType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftentraiddevicedata',
            name='trustType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='activationLockBypassCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='androidSecurityPatchLevel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='azureADDeviceId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='configurationManagerClientEnabledFeatures',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceCategoryDisplayName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceEnrollmentType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceHealthAttestationState',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='deviceRegistrationState',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='easDeviceId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='emailAddress',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='enrollmentProfileName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='ethernetMacAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='exchangeAccessState',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='exchangeAccessStateReason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='iccid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='imei',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='managementAgent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='meid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='partnerReportedThreatState',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='phoneNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='remoteAssistanceSessionErrorDetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='remoteAssistanceSessionUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='requireUserEnrollmentApproval',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='serialNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='subscriberCarrier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='totalStorageSpaceInBytes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='udid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='userDisplayName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='userId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='userPrincipalName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microsoftintunedevicedata',
            name='wiFiMacAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='firstFoundDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='ipAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualysdevice',
            name='osPlatform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='associatedPerson_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='associatedPerson_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='associatedPerson_viaLogin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='os_build',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='os_majorVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='os_minorVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='os_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='os_platform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophoscentraldevicedata',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='given_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='upn',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
