# Generated by Django 5.0.6 on 2024-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_cloudflarezerotrustdevice_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='compliant',
            field=models.BooleanField(default=False),
        ),
    ]
