# Generated by Django 5.0.7 on 2024-07-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_userdata_highest_authentication_strength_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdStrikeFalconPreventionPolicy',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('platform_name', models.CharField(max_length=200, null=True)),
                ('enabled', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrowdStrikeFalconPreventionPolicySetting',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('prevention_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.crowdstrikefalconpreventionpolicy')),
            ],
        ),
    ]
