# Generated by Django 5.0.7 on 2024-07-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_crowdstrikefalconpreventionpolicy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdstrikefalconpreventionpolicysetting',
            old_name='id',
            new_name='id_cs',
        ),
    ]
