# Generated by Django 5.0.7 on 2024-07-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_rename_id_crowdstrikefalconpreventionpolicysetting_id_cs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdstrikefalconpreventionpolicysetting',
            old_name='id_cs',
            new_name='id',
        ),
    ]
