# Generated by Django 5.0.7 on 2025-03-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_rename_id_cs_crowdstrikefalconpreventionpolicysetting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='job_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='network_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
