# Generated by Django 5.0.7 on 2025-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_userdata_department_userdata_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_logon_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
