# Generated by Django 5.0.7 on 2025-03-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_userdata_last_logon_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_at_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
