# Generated by Django 5.0.7 on 2025-04-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_remove_userdata_fido2_authentication_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='persona',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
