# Generated by Django 6.0 on 2025-12-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crowdstrikefalconpreventionpolicysetting',
            name='prevention_policy',
        ),
        migrations.AddField(
            model_name='userdata',
            name='persona_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.personagroup'),
        ),
        migrations.DeleteModel(
            name='CrowdStrikeFalconPreventionPolicy',
        ),
        migrations.DeleteModel(
            name='CrowdStrikeFalconPreventionPolicySetting',
        ),
    ]
