# Generated by Django 6.0 on 2025-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_personagroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagroup',
            old_name='name',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='personagroup',
            name='object_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
