# Generated by Django 6.0 on 2025-12-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_persona_remove_personagroup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagroup',
            name='persona',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='main.persona'),
            preserve_default=False,
        ),
    ]
