# Generated by Django 6.0 on 2025-12-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_personagroup_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagroup',
            name='persona',
        ),
    ]
