# Generated by Django 6.0 on 2025-12-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_remove_personagroup_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagroup',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.persona'),
        ),
    ]
