# Generated by Django 6.0 on 2025-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_personagroup_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagroup',
            name='priority',
        ),
        migrations.AddField(
            model_name='persona',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
