# Generated by Django 6.0 on 2025-12-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_remove_personagroup_priority_persona_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.persona'),
        ),
    ]
