# Generated by Django 6.0 on 2026-01-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_alter_userdata_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('Cloudflare Zero Trust', 'Cloudflare Zero Trust'), ('CrowdStrike Falcon', 'CrowdStrike Falcon'), ('Microsoft Defender for Endpoint', 'Microsoft Defender for Endpoint'), ('Microsoft Entra ID', 'Microsoft Entra ID'), ('Microsoft Intune', 'Microsoft Intune'), ('Sophos Central', 'Sophos Central'), ('Qualys', 'Qualys'), ('Tailscale', 'Tailscale')], max_length=35, null=True),
        ),
    ]
