# Generated by Django 6.0 on 2026-01-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_alter_integration_integration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailscaleDevice',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200, null=True)),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parentDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationTailscale', to='main.device')),
            ],
        ),
    ]
