# Generated by Django 6.0 on 2026-01-16 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_tailscaledevice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TailscaleDevice',
            new_name='TailscaleDeviceData',
        ),
    ]
