# Generated by Django 6.0 on 2026-01-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_rename_tailscaledevice_tailscaledevicedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailscaledevicedata',
            name='device_id',
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='authorized',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='blocksIncomingConnections',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='clientVersion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='connectedToControl',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='isExternal',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='keyExpiryDisabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='lastSeen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='machineKey',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='nodeId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='nodeKey',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='os',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='tailnetLockError',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='tailnetLockKey',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='updateAvailable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tailscaledevicedata',
            name='user',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tailscaledevicedata',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
