# Generated by Django 6.0 on 2026-01-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_remove_tailscaledevicedata_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareZeroTrustDeviceData',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200, null=True)),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('osPlatform', models.CharField(max_length=200, null=True)),
                ('endpointType', models.CharField(max_length=25, null=True)),
                ('version', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('os_version', models.CharField(max_length=200, null=True)),
                ('manufacturer', models.CharField(max_length=200, null=True)),
                ('ip', models.CharField(max_length=200, null=True)),
                ('gateway_device_id', models.CharField(max_length=200, null=True)),
                ('serial_number', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parentDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrationCloudflareZeroTrust', to='main.device')),
            ],
        ),
        migrations.DeleteModel(
            name='CloudflareZeroTrustDevice',
        ),
    ]
