# Generated by Django 6.0 on 2026-01-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_cloudflarezerotrustdevicedata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudflarezerotrustdevicedata',
            options={'verbose_name': 'Cloudflare Zero Trust Device', 'verbose_name_plural': 'Cloudflare Zero Trust Devices'},
        ),
        migrations.AlterModelOptions(
            name='crowdstrikefalcondevicedata',
            options={'verbose_name': 'CrowdStrike Falcon Device', 'verbose_name_plural': 'CrowdStrike Falcon Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicecompliancesettings',
            options={'verbose_name': 'Device Compliance Setting', 'verbose_name_plural': 'Device Compliance Settings'},
        ),
        migrations.AlterModelOptions(
            name='microsoftdefenderforendpointdevicedata',
            options={'verbose_name': 'Microsoft Defender for Endpoint Device', 'verbose_name_plural': 'Microsoft Defender for Endpoint Devices'},
        ),
        migrations.AlterModelOptions(
            name='microsoftentraiddevicedata',
            options={'verbose_name': 'Microsoft Entra ID Device', 'verbose_name_plural': 'Microsoft Entra ID Devices'},
        ),
        migrations.AlterModelOptions(
            name='microsoftintunedevicedata',
            options={'verbose_name': 'Microsoft Intune Device', 'verbose_name_plural': 'Microsoft Intune Devices'},
        ),
        migrations.AlterModelOptions(
            name='qualysdevice',
            options={'verbose_name': 'Qualys Device', 'verbose_name_plural': 'Qualys Devices'},
        ),
        migrations.AlterModelOptions(
            name='sophoscentraldevicedata',
            options={'verbose_name': 'Sophos Central Device', 'verbose_name_plural': 'Sophos Central Devices'},
        ),
        migrations.AlterModelOptions(
            name='tailscaledevicedata',
            options={'verbose_name': 'Tailscale Device', 'verbose_name_plural': 'Tailscale Devices'},
        ),
    ]
