# Generated by Django 6.0 on 2026-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_alter_cloudflarezerotrustdevicedata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecompliancesettings',
            name='tailscale',
            field=models.BooleanField(null=True),
        ),
    ]
