# Generated by Django 6.0 on 2026-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_devicecompliancesettings_tailscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='last_connection_test_at',
            field=models.DateTimeField(null=True),
        ),
    ]
